version: '3.8'

services:
  # Override app service for development
  app:
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  # Override db service for development
  db:
    ports:
      - "5432:5432"

  # Override redis service for development
  redis:
    ports:
      - "6379:6379"